FROM node:20-alpine
WORKDIR /usr/src/app
COPY package.json package-lock.json* ./
COPY ./frontend/package.json ./package.json
RUN npm ci --silent
COPY ./frontend /usr/src/app
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]
